name: NATS C Client CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake .. -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_TLS_USE_OPENSSL_1_1_API=ON
    - name: build
      run: cmake --build build
    - name: install deps
      shell: bash --noprofile --norc -x -eo pipefail {0}
      run: |
        # Install the deps in the build directory
        cd build
        ../install_deps.sh
    - name: test
      shell: bash --noprofile --norc -x -eo pipefail {0}
      run: |
        cd build
        test/testsuite
        mv list.txt ../test
        cmake ..
        export NATS_TEST_SERVER_VERSION="$(./nats-server/nats-server -v)"
        export NATS_TEST_TRAVIS=yes
        export PATH=$RUNNER_WORKSPACE/nats.c/build/nats-server:$PATH
        ctest --timeout 60 --output-on-failure

#   build-windows:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [windows-latest, windows-2016]
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: configure
#       run: |
#         mkdir build
#         cd build
#         cmake .. -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_TLS_USE_OPENSSL_1_1_API=ON
#     - name: build
#       run: cmake --build build
#     - name: test
#       run: |
#         cd build
#         ctest
